apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openarabic
  namespace: openarabic
spec:
  interval: 5m
  chart:
    spec:
      chart: open-arabic-helm
      version: '>=0.1.0'
      sourceRef:
        kind: HelmRepository
        name: openarabic
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2